{{- if .Values.p2p.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cardano.configName" . }}-p2p
data:
{{ (tpl (.Files.Glob "files/p2p.yaml").AsConfig . ) | indent 2 }}
{{- end }}
