{{- if eq .Values.environment.name "testnet" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cardano.configName" . }}-testnet
data:
  readiness.sh: |
{{ (tpl (.Files.Get "files/readiness.sh")  . ) | indent 4 }}
  p2p.sh: |
{{ (tpl (.Files.Get "files/p2p.sh")  . ) | indent 4 }}
  producer-topology.json: |
{{ (tpl (.Files.Get "files/testnet/producer-topology.json") . ) | indent 4 }}
  relay-topology.json: |
{{ (tpl (.Files.Get "files/testnet/relay-topology.json") . ) | indent 4 }}
  config.json: |
{{ (tpl (.Files.Get "files/testnet/config.json") . ) | indent 4 }}
binaryData:
{{- $root := . }}
{{- $location := "files/testnet/*.json.gz" }}
{{- range $path, $bytes := .Files.Glob $location }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc | quote }}
{{- end }}
{{- end }}
