{{- $fullName := include "cardano.fullname" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cardano.configName" . }}-topology-updater
data:
  cardanoNodePort: "3001"
{{- if eq .Values.environment.name "testnet" }}
  networkMagic: "1097911063"
{{- end }}
{{- if eq .Values.environment.name "mainnet" }}
  networkMagic: "764824073"
{{- end }}
  ipVersion: {{ .Values.p2p.ipVersion | default 4 | quote }}
  maxPeers: {{ .Values.p2p.maxPeers | default 15 | quote }}  # Maximum number of peers to return on successful fetch (note that a single peer may include valency of up to 3)
{{- if .Values.producer.enabled }}
# *Additional* custom peers to (IP,port[,valency]) to add to your target topology.json
# eg: "10.0.0.1,3001|10.0.0.2,3002|relays.mydomain.com,3003,3"
  customPeers: "{{ $fullName }}-producer-0.{{ $fullName }}-headless.{{ .Release.Namespace }}.svc.cluster.local,3001,1"
{{- else }}
  customPeers: ""
{{- end }}
  ekgHost: "{{ $fullName }}-relay-0.{{ $fullName }}-headless.{{ .Release.Namespace }}.svc.cluster.local"
  ekgPort: "12789"
  ekgTimeout: {{ .Values.p2p.ekgTimeout | default 5 | quote }}
