apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cardano.secretName" . }}
data:
  redis-username: {{ .Values.secrets.redisUsername | b64enc }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc }}
